Nessie CLI: publish Docker images (#8935)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -749,6 +749,7 @@ jobs:
           echo "DOCKER_IMAGE=${DOCKER_REGISTRY}:5000/nessie-testing" >> ${GITHUB_ENV}
           echo "DOCKER_GC_IMAGE=${DOCKER_REGISTRY}:5000/nessie-gc-testing" >> ${GITHUB_ENV}
           echo "DOCKER_SERVER_ADMIN_IMAGE=${DOCKER_REGISTRY}:5000/nessie-server-admin-testing" >> ${GITHUB_ENV}
+          echo "DOCKER_CLI_IMAGE=${DOCKER_REGISTRY}:5000/nessie-cli-testing" >> ${GITHUB_ENV}
 
       - name: Prepare Gradle build cache
         uses: ./.github/actions/ci-incr-build-cache-prepare
@@ -773,6 +774,12 @@ jobs:
             -d "Dockerfile-admintool" \
             ${DOCKER_SERVER_ADMIN_IMAGE}
 
+          tools/dockerbuild/build-push-images.sh \
+            -g ":nessie-cli" \
+            -p "cli/cli" \
+            -d "Dockerfile-cli" \
+            ${DOCKER_CLI_IMAGE}
+
       - name: Cleanup buildx
         run: |
           docker buildx use default
@@ -792,6 +799,10 @@ jobs:
           docker pull ${DOCKER_SERVER_ADMIN_IMAGE}:latest-java
           docker pull ${DOCKER_SERVER_ADMIN_IMAGE}:${DOCKER_VERSION}
           docker pull ${DOCKER_SERVER_ADMIN_IMAGE}:${DOCKER_VERSION}-java
+          docker pull ${DOCKER_CLI_IMAGE}:latest
+          docker pull ${DOCKER_CLI_IMAGE}:latest-java
+          docker pull ${DOCKER_CLI_IMAGE}:${DOCKER_VERSION}
+          docker pull ${DOCKER_CLI_IMAGE}:${DOCKER_VERSION}-java
           cat <<! >> $GITHUB_STEP_SUMMARY
           ## Docker images
           
@@ -853,6 +864,23 @@ jobs:
 
             \`\`\`
             $(docker logs nessie-server-admin)
+            \`\`\`
+          !
+            exit 1
+          fi
+
+      - name: Check if CLI Docker Java image works
+        run: |
+          if docker run --rm --name nessie-cli ${DOCKER_CLI_IMAGE}:latest-java --help | grep -q "Usage: nessie-cli.jar"; then
+            echo "## CLI Java Docker image smoke test: PASSED" >> $GITHUB_STEP_SUMMARY  
+            echo "CLI Java Docker image smoke test: PASSED"
+          else
+           echo "CLI Java Docker image smoke test: FAILED" > /dev/stderr
+            cat <<! >> $GITHUB_STEP_SUMMARY
+            ## CLI Java Docker image FAILED
+
+            \`\`\`
+            $(docker logs nessie-cli)
             \`\`\`
           !
             exit 1
